[package]
name = "neveno-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
neveno-core = { path = "../core" }
tokio = { version = "1.41.1", features = ["rt-multi-thread", "macros"] }
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0.93"
